3.6.12 - improved release version check (#92)
* release: 3.6.10

* 3.6.11 - added source header check before release

* 3.6.11 - updated in readme and added changelog

* updated plug-in header to 3.6.11

* Move to 3.6.12

* add fix to changelog for 3.6.12

---------

Co-authored-by: Sertii <36940685+Sreini@users.noreply.github.com>

diff --git a/bin/check-version b/bin/check-version
--- a/bin/check-version
+++ b/bin/check-version
@@ -9,9 +9,15 @@ TAG_VERSION="${1:-${GITHUB_REF#refs/tags/}}"
 
 # Stable tag from readme.txt
 README_VERSION=$(grep -m 1 "^Stable tag:" readme.txt | awk '{print $3}')
+SOURCE_VERSION=$(grep "Version:" tiny-compress-images.php | head -n 1 | cut -d ':' -f 2 | xargs)
 
 if [ "$TAG_VERSION" != "$README_VERSION" ]; then
     echo "Error: Tag: $TAG_VERSION, readme.txt: $README_VERSION"
+    exit 1
+fi
+
+if [ "$TAG_VERSION" != "$SOURCE_VERSION" ]; then
+    echo "Error: Tag: $TAG_VERSION, tiny-compress-images.php: $SOURCE_VERSION"
     exit 1
 fi
 
